### ISSUE TITLE
Alternate zig version

### ISSUE THREAD

**Issue by kprotty** [contextfreecode/async-exec#1]
Noticed that the zig test is attempting to wait concurrently, and that it's going through `std.event.Loop.instance.?.sleep` to do so. For what it's worth, [`std.time.sleep`](https://github.com/ziglang/zig/blob/master/lib/std/time.zig#L18-L20) already acts as such a proxy. Here's an example:

```zig
const std = @import("std");

pub const io_mode = .evented;

pub fn main() !void {
    const concurrency = 10;
    const delay_ns = 1 * std.time.ns_per_s;
    const error_ns = 20 * std.time.ns_per_ms;

    var timer = try std.time.Timer.start();

    const started_ns = timer.read();
    std.log.info("started waiting for {}ms in {} tasks", .{
        delay_ns / std.time.ns_per_ms, 
        concurrency,
    });

    defer {
        const elapsed_ns = timer.read() - started_ns;
        std.log.info("finished in {}ms\n", .{
            elapsed_ns / std.time.ns_per_ms
        });

        std.debug.assert(elapsed_ns >= delay_ns - error_ns);
        std.debug.assert(elapsed_ns <= delay_ns + error_ns);
    }    

    var frames: [concurrency]@Frame(std.time.sleep) = undefined;
    for (frames) |*f| f.* = async std.time.sleep(delay_ns);
    for (frames) |*f| await f;
}
```

The language and standard library are also changing rapidly and sleep integration, or even the event loop as a whole, may be moved around and re-shuffled. Zig is also yet to add something akin to the [`Duration`](https://doc.rust-lang.org/std/time/struct.Duration.html) and [`Instant`](https://doc.rust-lang.org/std/time/struct.Instant.html) abstractions.

**Comment by tjpalmer** [comment]
I just swapped out `std.event.Loop.instance.?.sleep` for `std.time.sleep`, and it works the same as before, and I see it making the call in the time.zig source, too. Thanks much for the tip.

**Comment by tjpalmer** [comment]
Here's my change: https://github.com/contextfreecode/async-exec/commit/22aae629242cf71518d941a3555d92ca8d0ce35c

Is that the gist?

**Comment by kprotty** [comment]
Yup, that's about it. Also maybe use `std.time.Timer` as opposed to `std.time.nanoTimestamp()` since the latter uses system time which may go backwards if set by the user. In practice for benchmarking however, this isn't really a big deal.

**Comment by tjpalmer** [comment]
So I swapped out the `nanoTimestamp` for a `Timer` in my elapsed calculation in my main code, but in my hack event loop I had a problem. If I tried making a global Timer, I got a compiler error message. I can give more details if you want.

**Comment by kprotty** [comment]
@tjpalmer Sure. I assume it's regarding not unwrapping the error from `std.time.Timer.start()`?

**Comment by tjpalmer** [comment]
I don't think that's it. Here's an example error message just for a bogus global timer that I put in for testing:
```zig
zig-linux-x86_64-0.8.0/lib/std/os/linux.zig:749:73: error: unable to evaluate constant expression
    return syscall2(.clock_getres, @bitCast(usize, @as(isize, clk_id)), @ptrToInt(tp));
                                                                        ^
zig-linux-x86_64-0.8.0/lib/std/os.zig:4703:38: note: called from here
    switch (errno(system.clock_getres(clk_id, res))) {
                                     ^
zig-linux-x86_64-0.8.0/lib/std/time.zig:197:28: note: called from here
            os.clock_getres(monotonic_clock_id, &res) catch return error.TimerUnsupported;
                           ^
./count.zig:49:31: note: called from here
const t = std.time.Timer.start();
                              ^
```

**Comment by kprotty** [comment]
start() calls into the OS to get the current time and resolution. You can't do this in the global scope (unless the operation can be done at compile time) as it's not running anywhere.

**Comment by tjpalmer** [comment]
Thanks much for the info.
